import './styles/App.css';

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="background"></div>
        {children}
      </body>
    </html>
  );
}
